### ISSUE TITLE
copying to stdout breaks with very short duration jobs

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#124]
```yaml
- work-command:
    service: echosleepshort
    command: bash
    params:  "-c \"for i in {1..5}; do echo $i;done\""
```

- Start 2 nodes, `foo.yml` and `bar.yml`
- `nc -U /tmp/foo.sock`
- `work submit bar echosleepshort`

job completes with success, but the following errors appear.

error on bar `ERROR 2020/08/28 18:09:20 Write error in control service: stream 0 was reset with error code 499`

error on foo `ERROR 2020/08/28 18:09:20 Error copying to stdout file /tmp/receptor/foo/bSEyWDfT/stdout: Read on stream 0 canceled with error code 499`

this breaks `work results {workID}` of course as the stdout file is never copied

I think it's a race condition, because if I change command to `echo $i; sleep 1` then everything works fine.

foo.yml

```yaml
---
- node:
    id: foo
    allowedpeers: bar
- control-service:
    service: control
    filename: /tmp/foo.sock
- tcp-listener:
    port: 2222
```

bar.yml
```yaml
---
- node:
    id: bar
    allowedpeers: foo
- tcp-peer:
    address: localhost:2222
    redial: true
- work-command:
    service: echosleepshort
    command: bash
    params:  "-c \"for i in {1..5}; do echo $i;done\""
```
