### ISSUE TITLE
kubernetes pod stays in running

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#191]
Tried this out with a local minikube setup

I got a hang when trying the following (I see the pod is created and running, but it never terminates)

```yaml
- work-kubernetes:
    worktype: kubeit
    namespace: default
    command: "bash -c \"while read -r line; do echo $line; sleep 0.5; done\""
    authmethod: params
    kubehost: http://127.0.0.1:44355/
    kubeapipath: api/v1
    kubeusername: sbf
    kubepassword: sbf
    allowruntimecommand: true
```
`seq 10 | receptorctl --socket /tmp/foo.sock work submit kubeit --payload - -f --param kube_image=centos:8 --rm`

if I add in my own `kube_command` it will work

`seq 10 | receptorctl --socket /tmp/foo.sock work submit kubeit --payload - -f --param kube_image=centos:8 --rm --param kube_command='echo HI'`

also if I change `authmethod` to `kubeconfig` it will work

```yaml
- work-kubernetes:
    worktype: kubeit
    namespace: default
    command: "bash -c \"while read -r line; do echo $line; sleep 0.5; done\""
    kubeconfig: /home/sfoster/.kube/config
    authmethod: kubeconfig
    allowruntimecommand: true
```

Suspicion is that the command isn't getting a stdin -- maybe receptor isn't passing it to the kube api, or the kube api not getting it to the container
