### ISSUE TITLE
k8s bug: Work status says job succeeded when container failed

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#209]
I experienced a scenario where a container failed, but `work status` said the job finished and succeeded.

work unit
```yaml
- work-kubernetes:
    worktype: kubeit
    image: alpine/socat
    namespace: default
    command: "bash -c \"while read -r line; do echo $line; sleep 0.5; done\""
    kubeconfig: /home/sfoster/.kube/config
    authmethod: kubeconfig
```
the image doesn't have bash, I can see the pod error `Error: failed to start container "worker": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`

However the work results didn't reflect that error

```
{'iyU524yu': {'Detail': 'Finished',
              'ExtraData': {'Command': 'bash -c "while read -r line; do echo '
                                       '$line; sleep 0.5; done"',
                            'Image': 'alpine/socat',
                            'KubeAPIPath': '',
                            'KubeBearerToken': '',
                            'KubeHost': '',
                            'KubeNamespace': 'default',
                            'KubePassword': '',
                            'KubeTLSCAData': '',
                            'KubeUsername': '',
                            'KubeVerifyTLS': True,
                            'Params': '',
                            'PodName': 'kubeit-bfp8m'},
              'State': 2,
              'StateName': 'Succeeded',
              'StdoutSize': 0,
              'WorkType': 'kubeit'}}
```
