### ISSUE TITLE
Back-end TLS fails in default configuration

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#225]
The following configuration fails with `ERROR 2020/10/12 16:38:21 Backend receiving error GetConfigForClient callback not properly configured`:

```
- tls-server:
    name: backend
    cert: /etc/receptor/backend.crt
    key: /etc/receptor/backend.key

- tcp-listener:
    port: 2222
    tls: backend
```

This is happening because `VerifyClientNodeId` is set to `default:true` in the config object.  Setting this to `false` in the `tls-server` config fixes the error.

Options for solving this:
* Default `VerifyClientNodeId` to `false`
* Explicitly set `GetConfigForClient` to nil when initializing backend TLS, since this function doesn't work there anyway
* Figure out some way to have "not set" be different from true or false, and have "not set" mean true for Receptor-level TLS and false for backend TLS.
