### ISSUE TITLE
receptorctl hangs if control-service tcp tls enabled

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#245]
run a node with the following config

```yaml
---
- node:
    id: foo
    allowedpeers: bar

- control-service:
    tcptls: server
    tcplisten: 8888

- tls-server:
    name: server
    cert: /home/sfoster/myca/pki/issued/server.crt
    key: /home/sfoster/myca/pki/private/server.key

- tcp-listener:
    port: 2222
```
This command should error out (no tls on client side), but instead it hangs,

`receptorctl --socket tcp://localhost:8888 status`

Our receptor listener actually accepts in this case, which is strange https://github.com/project-receptor/receptor/blob/ff69d0031711e7aa05f52ad115bdc522da8f505e/pkg/controlsvc/controlsvc.go#L324

from log
`INFO 2020/11/04 10:05:56 Client connected to control service`
