### ISSUE TITLE
Do not require image w/ work-kubernetes when using allowruntimeparams

### ISSUE THREAD

**Issue by shanemcd** [ansible/receptor#283]
With the following config:

```
- work-kubernetes:
    worktype: ocp
    namespace: awx
    authmethod: kubeconfig
    allowruntimeauth: true
    allowruntimeparams: true
```

I am seeing the error:

```
$ ./receptor --config ~/awx/tools/docker-compose/receptor.conf
Error: must specify a container image to run
```

I want to pass this only via runtime pod spec.
