### ISSUE TITLE
k8s work unit fails because container exited before attaching stdin stream

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#489]
This bug occurs occasionally while running make test.

Here is the work unit status from the following functional test `TestWork/kube_worker/work_submit_while_remote_node_is_down`

```
{
  "State": 3,
  "Detail": "Stream error running pod: stdin: Internal error occurred: error attaching to container: container is in CONTAINER_EXITED state, stdout: http2: response body closed",
  "StdoutSize": 10,
  "WorkType": "echosleepshort",
  "ExtraData": {
    "Image": "alpine",
    "Command": "sh -c \"for i in `seq 1 5`; do echo $i;done\"",
    "Params": ""
  }
  etc.
}
```

Interestingly the pod ran and we got back the full stdout (10 bytes). This work unit doesn't even have stdin.

Seems the pod is running and finishing before we can attach a stdin stream, but this stream isn't needed in this case. This work unit should have succeeded.

**Comment by fosterseth** [comment]
add this to your receptor node conf

```yaml
- work-kubernetes:
    worktype: kubeit2
    authmethod: runtime
    allowruntimeauth: true
    allowruntimepod: true
    allowruntimeparams: true
```

create pod.yml
```yaml
apiVersion: v1
kind: Pod
metadata:
    generateName: myapp-pod-
    labels:
        app: myapp
spec:
    containers:
    - name: worker
      image: busybox
      command: ['sh', '-c', 'echo The Pod is running && sleep 0 && exit 0']
      # resources:
      #     limits:
      #         memory: "1000000Mi"
    restartPolicy: Never
```

`minikube start`, start receptor process, then submit work

`receptorctlfoo work submit kubeit2 --param secret_kube_pod=@/home/sbf/sockceptor/pod.yml --param secret_kube_config=@/home/sbf/.kube/config --no-payload`
