### ISSUE TITLE
Receptor can't be started with pre-defined pod specification

### ISSUE THREAD

**Issue by kurokobo** [ansible/receptor#712]
## Description

Defining `work-kubernetes` with pre-defined `pod` without `allowruntimecommand` or `allowruntimepod` causes following error on startup.

```bash
$ ./receptor -c ./receptor.yml 
Error: must specify a container image to run
```

## Version

Using Receptor built by `make receptor` on upstream devel branch.

```bash
$ receptorctl --socket /tmp/receptor.sock version
Warning: receptorctl and receptor are different versions, they may not be compatible
receptorctl  1.3.0
receptor     v1.3.0+g8f8481c
```

## Steps to reproduce

Start Receptor with following configuration file.

```yaml
---
- local-only:
- node:
    id: demo
- log-level:
    level: debug
- control-service:
    service: control
    filename: /tmp/receptor.sock
- work-kubernetes:
    worktype: demo
    authmethod: kubeconfig
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    pod: /tmp/pod.yml
```

```bash
$ ./receptor -c ./receptor.yml 
Error: must specify a container image to run
```

Appending `allowruntimecommand: true` or `allowruntimepod: true` which do not actually make sense to the configuration file solves the issue.

```yaml
...
- work-kubernetes:
    worktype: demo
    authmethod: kubeconfig
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    pod: /tmp/pod.yml
    allowruntimecommand: true     👈👈👈
```

```bash
$ ./receptor -c ./receptor.yml 
INFO 2022/12/20 06:50:45 Running control service control
INFO 2022/12/20 06:50:45 Initialization complete
...
```

## Additional information

Following validation for `cfg.Image == ""` should trigger only when `cfg.Pod` is empty.

https://github.com/ansible/receptor/blob/8f8481ce94b76ed6d90c8936baf071111275960d/pkg/workceptor/kubernetes.go#L1271-L1276
