### ISSUE TITLE
Jobs stuck in pending even when remote node comes back online

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#74]
Steps to reproduce,

1. start local control node (`foo.yml`)
2. start remote node (`bar.yml`) and allow connections to establish
3. kill bar node
4. on foo:control, `work submit bar 100cat`
5. job will start in pending state as expected
6. bring bar back up
7. work remains in pending and never starts
8. If you run line 4 again, a new job will start and run successfully.

It does work properly if you skip steps 2 and 3. If you just start`foo`, then submit job, then bring up `bar` (for the first time), the work will starting running.

Note,

`work submit` calls `connectToRemote()` and I've noticed a hang occurs on `netceptor/conn.go`
```golang
qc, err := quic.Dial(pc, rAddr, s.nodeID, tls, cfg
```

foo.yml
```
---
- node:
    id: foo
    allowedpeers: bar,fish

- control-service:
    service: control
    filename: /tmp/foo.sock

- tcp-listener:
    port: 2222
```

bar.yml

```
---
- node:
    id: bar

- tcp-peer:
    address: localhost:2222
    redial: true

- control-service:
    service: control
    filename: /tmp/bar.sock

- work-command:
    service: 100cat
    command: bash
    params: "-c \"seq 100 | /home/sfoster/sockceptor/sleepcat.sh\""
```
