### ISSUE TITLE
Ncat: Connection refused error after restarting control service

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#84]
1. start node with `./receptor -c foo.yml`
2. `nc -U /tmp/foo.sock` > `work start 100cat`
3. sigterm node to kill it
4. start node again with `./receptor -c foo.yml`
5. `nc -U /tmp/foo.sock` > error `Ncat: Connection refused`

step 2 seems to be necessary -- a long running task. If I run other commands like `status` or `work list` or start a short-running job like `work start sleepcat` with small payload, then the error on step 5 doesn't occur.

foo.yml
```
---
- node:
    id: foo
    allowedpeers: bar,fish

- control-service:
    service: control
    filename: /tmp/foo.sock

- tcp-listener:
    port: 2222

- work-command:
    service: 100cat
    command: bash
    params: "-c \"seq 100 | /home/sfoster/sockceptor/sleepcat.sh\""

```
